require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Project = require('../models/Project');
const User = require('../models/User');

// ── Unsplash image pool ────────────────────────────────────────────────────────
const IMG = {
  t1: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
  t2: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
  t3: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
  t4: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
  t5: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
  t6: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&q=80',
  t7: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
  t8: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
  t9: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
  t10: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
  t11: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
  t12: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
  pool: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
  gym:  'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
  club: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&q=80',
  int:  'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80',
  bed:  'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80',
  lob:  'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
  grdn: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
};

// ── Real Projects Data ─────────────────────────────────────────────────────────
// priceMin/priceMax are in LAKHS (₹1 Lakh = 100,000)
const PROJECTS = [

  // ════════════ DLF ════════════
  {
    name: 'DLF The Crest',
    slug: 'dlf-the-crest-gurgaon',
    builder: { name: 'DLF Limited', reraId: 'DLF/HARERA/2018' },
    location: 'Sector 54, Golf Course Road, Gurgaon',
    sector: 'Sector 54',
    corridor: 'Golf Course Road',
    pincode: '122003',
    status: 'Ready To Move',
    priceDisplay: '₹2.5 Cr – ₹8 Cr',
    pricePerSqft: '₹18,000 – ₹25,000',
    priceMin: 250, priceMax: 800,
    configurations: ['3 BHK (2,300 sqft)', '4 BHK (3,500 sqft)', 'Penthouse (6,500+ sqft)'],
    floorPlans: [
      { config: '3 BHK', area: '2,300 sqft', price: '₹2.5 Cr onwards' },
      { config: '4 BHK', area: '3,500 sqft', price: '₹4.5 Cr onwards' },
      { config: 'Penthouse', area: '6,500+ sqft', price: '₹8 Cr+' },
    ],
    possession: 'Ready', totalUnits: 360, totalTowers: 5, totalArea: '18 Acres', floors: 'G+43',
    rera: { number: 'RERA/GGM/2018/201', link: 'https://haryanarera.gov.in' },
    shortDescription: "DLF's most iconic ultra-luxury tower on Golf Course Road — ready to move, maximum privacy.",
    description: "DLF The Crest stands as Gurgaon's most coveted ultra-luxury address — 5 iconic towers on Golf Course Road. Each residence features panoramic city views, private elevator lobbies, imported marble floors and a 43-storey sky lounge. Ready to move, eliminating construction risk while offering immediate possession and rental income from day one.",
    highlights: ['Ready to move — immediate possession', "Golf Course Road's most iconic luxury address", 'Private elevator lobby on every floor', 'Sky Lounge and infinity pool on 43rd floor', 'DLF 5 micro-market — highest resale premium in Gurgaon', 'Strong NRI and HNI demand'],
    amenities: ['Grand Clubhouse', 'Infinity Sky Pool', 'Spa & Wellness', 'Golf Simulator', 'Squash & Tennis', 'Fine Dining', 'Business Centre', 'Concierge & Valet', '5-Tier Security', "Kids' Club", 'Party Terrace'],
    connectivity: ['Cyber City — 5 km', 'Huda City Centre Metro — 4 km', 'IGI Airport — 30 min', 'MG Road — 3 km', 'DLF Cyberhub — 6 km', 'Rapid Metro Golf Course — adjacent'],
    nearbyLandmarks: ['DLF Mega Mall — 1 km', 'Fortis Hospital — 3 km', 'Shri Ram School — 2 km', 'American Express — 3 km', 'Rapid Metro Station — 500m'],
    heroImage: IMG.t4, gallery: [IMG.t4, IMG.t2, IMG.pool, IMG.lob, IMG.bed, IMG.int],
    tags: ['luxury', 'ready-to-move', 'golf-course-road', 'dlf', 'ultra-luxury'],
    appreciationRate: '20–28% (3Y)', rentalYield: '2.8%',
    whyBuy: ['Ready to move — zero construction risk', "Gurgaon's most iconic address", 'Highest resale premium market', 'Strong NRI investment demand'],
    faqs: [
      { q: 'Is DLF The Crest ready to move?', a: 'Yes. DLF The Crest has received OC and all units are ready for immediate possession.' },
      { q: 'What is the resale value of DLF The Crest?', a: 'DLF The Crest commands a significant resale premium in DLF 5 — one of Gurgaon\'s highest-value micro-markets. Units have appreciated 15–20% over 3 years.' },
    ],
    isFeatured: true, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'DLF The Crest Gurgaon – Ultra Luxury Ready To Move on Golf Course Road',
    metaDescription: 'DLF The Crest Gurgaon — ultra luxury 3, 4 BHK & penthouse on Golf Course Road. Ready to move. Price from ₹2.5 Cr. Free site visit.',
    metaKeywords: 'DLF The Crest, DLF Gurgaon, Golf Course Road luxury apartments, DLF 5 Gurgaon, ready to move luxury Gurgaon',
  },

  {
    name: 'DLF Privana South',
    slug: 'dlf-privana-south-gurgaon',
    builder: { name: 'DLF Limited', reraId: 'DLF/HARERA/2024' },
    location: 'Sector 77, SPR Road, Gurgaon',
    sector: 'Sector 77',
    corridor: 'SPR Road',
    pincode: '122004',
    status: 'New Launch',
    priceDisplay: '₹6 Cr – ₹18 Cr',
    pricePerSqft: '₹22,000 – ₹28,000',
    priceMin: 600, priceMax: 1800,
    configurations: ['4 BHK (2,800 sqft)', '4.5 BHK (3,800 sqft)', '5 BHK (5,000 sqft)'],
    floorPlans: [
      { config: '4 BHK', area: '2,800 sqft', price: '₹6 Cr onwards' },
      { config: '4.5 BHK', area: '3,800 sqft', price: '₹9 Cr onwards' },
      { config: '5 BHK', area: '5,000 sqft', price: '₹12 Cr onwards' },
    ],
    possession: 'December 2028', totalUnits: 800, totalTowers: 8, totalArea: '42 Acres', floors: 'G+46',
    rera: { number: 'RERA/GGM/2024/720', link: 'https://haryanarera.gov.in' },
    shortDescription: "DLF's most exclusive new launch — ultra luxury 4 & 5 BHK residences on SPR Road with golf views.",
    description: "DLF Privana South is DLF's most ambitious ultra-luxury development in Gurgaon — a landmark 42-acre integrated township on SPR Road with Golf Course Extension views. Targeting India's top 1% of homebuyers, Privana South offers spacious 4 and 5 BHK residences with private golf access, concierge living and DLF's signature quality. The project sold out in hours at launch, validating Gurgaon's premium real estate demand.",
    highlights: ['DLF\'s most exclusive launch — sold 1,113 flats in 3 days at launch', 'Golf Course Extension Road views from all units', 'Private golf access for residents', '42-acre super township', 'Ultra-luxury segment starting ₹6 Cr', 'RERA registered'],
    amenities: ['Private Golf Course Access', 'Super Clubhouse (1 lakh sqft)', 'Olympic Pool', 'Spa & Wellness Centre', 'Sky Lounge & Dining', 'Tennis & Squash', 'Business Centre', 'Pet Park', 'Concierge 24/7', 'EV Charging Hub'],
    connectivity: ['Golf Course Extension Road — 2 km', 'NH-48 — 8 km', 'Sohna Road — 6 km', 'Cyber City — 18 km', 'IGI Airport — 35 min'],
    nearbyLandmarks: ['GD Goenka School — 5 km', 'Medanta Hospital — 20 km', 'South Point Mall — 8 km', 'Emaar Digi Homes — 10 km'],
    heroImage: IMG.t1, gallery: [IMG.t1, IMG.t5, IMG.pool, IMG.club, IMG.int, IMG.lob],
    tags: ['ultra-luxury', 'new-launch', 'spr-road', 'dlf', 'golf-views'],
    appreciationRate: '30–40% (3Y)', rentalYield: '2.5%',
    whyBuy: ['DLF\'s flagship ultra-luxury project in 2025', 'Golf access — unique lifestyle feature', 'Best SPR Road address', 'Long-term HNI demand drives resale'],
    faqs: [
      { q: 'What is DLF Privana South price?', a: 'DLF Privana South starts from ₹6 Cr for a 4 BHK (2,800 sqft). The project targets luxury homebuyers and investors.' },
      { q: 'Is DLF Privana South RERA approved?', a: 'Yes. RERA number: RERA/GGM/2024/720. Verify at haryanarera.gov.in.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'DLF Privana South Sector 77 Gurgaon – Ultra Luxury SPR Road New Launch',
    metaDescription: 'DLF Privana South Gurgaon — ultra luxury 4 & 5 BHK on SPR Road from ₹6 Cr. Golf views, premium township. Book now.',
    metaKeywords: 'DLF Privana South, DLF Privana Gurgaon, SPR Road luxury, new launch Gurgaon 2025, DLF ultra luxury',
  },

  {
    name: 'DLF The Arbour',
    slug: 'dlf-the-arbour-gurgaon',
    builder: { name: 'DLF Limited', reraId: 'DLF/HARERA/2023' },
    location: 'Sector 63, Golf Course Extension Road, Gurgaon',
    sector: 'Sector 63',
    corridor: 'Golf Course Extension Road',
    pincode: '122102',
    status: 'Under Construction',
    priceDisplay: '₹6.5 Cr – ₹12 Cr',
    pricePerSqft: '₹24,000 – ₹30,000',
    priceMin: 650, priceMax: 1200,
    configurations: ['4 BHK (2,680 sqft)', '4 BHK+Study (3,000 sqft)'],
    floorPlans: [
      { config: '4 BHK', area: '2,680 sqft', price: '₹6.5 Cr onwards' },
      { config: '4 BHK+Study', area: '3,000 sqft', price: '₹8.5 Cr onwards' },
    ],
    possession: 'June 2027', totalUnits: 1,137, totalTowers: 12, totalArea: '25 Acres', floors: 'G+40',
    rera: { number: 'RERA/GGM/2023/611', link: 'https://haryanarera.gov.in' },
    shortDescription: "DLF's luxury 4 BHK project on Golf Course Extension Road — sold 1,113 units at launch in 3 days.",
    description: "DLF The Arbour on Golf Course Extension Road made history by selling all 1,113 units in its first phase within 3 days of launch — at prices starting ₹7 Cr. This ultra-luxury development in Sector 63 offers spacious 4 BHK residences with premium amenities, resort-style clubhouse and DLF's guaranteed quality delivery on GCER's most coveted address.",
    highlights: ['All units sold at launch — validates extreme demand', '1,113 units across 12 towers', 'GCER\'s most premium 4 BHK address', 'Resort-style clubhouse on 5-acre podium', 'DLF guaranteed quality delivery', 'Top investment in Gurgaon'],
    amenities: ['Mega Clubhouse (70,000 sqft)', 'Lap Pool & Splash Zone', 'Gym & Wellness', 'Indoor Sports', 'Mini Theatre', 'Co-working Lounge', 'Kids Zone', 'Pet Park', 'Concierge'],
    connectivity: ['Golf Course Extension Road — direct', 'Golf Course Road — 8 km', 'NH-48 — 12 km', 'Vatika Chowk — 6 km', 'Cyber City — 12 km', 'IGI Airport — 30 min'],
    nearbyLandmarks: ['GD Goenka University — 8 km', 'Fortis Hospital — 10 km', 'Emaar Palm Hills — 3 km'],
    heroImage: IMG.t2, gallery: [IMG.t2, IMG.t4, IMG.pool, IMG.club, IMG.int, IMG.bed],
    tags: ['ultra-luxury', 'under-construction', 'golf-course-extension', 'dlf', '4bhk'],
    appreciationRate: '28–35% (3Y)', rentalYield: '2.6%',
    whyBuy: ['Sold out in 3 days — rarest premium asset in Gurgaon', 'GCER top address', 'DLF quality assurance', 'Strong resale premium already 15-20% above launch'],
    faqs: [
      { q: 'Is DLF The Arbour sold out?', a: 'Yes, the initial launch phase was sold out in 3 days. Resale units are available through brokers at a premium.' },
    ],
    isFeatured: true, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'DLF The Arbour Sector 63 Gurgaon – Luxury 4 BHK Golf Course Extension Road',
    metaDescription: 'DLF The Arbour Sector 63 Gurgaon — sold 1,113 units in 3 days. Luxury 4 BHK on Golf Course Extension Road from ₹6.5 Cr.',
    metaKeywords: 'DLF The Arbour, DLF Sector 63 Gurgaon, Golf Course Extension Road luxury, DLF 4 BHK Gurgaon 2025',
  },

  // ════════════ M3M ════════════
  {
    name: 'M3M Altitude',
    slug: 'm3m-altitude-sector-65-gurgaon',
    builder: { name: 'M3M India', reraId: 'M3M/HARERA/2023' },
    location: 'Sector 65, SPR Road, Gurgaon',
    sector: 'Sector 65',
    corridor: 'SPR Road',
    pincode: '122018',
    status: 'Under Construction',
    priceDisplay: '₹1.8 Cr – ₹3.2 Cr',
    pricePerSqft: '₹10,500 – ₹13,000',
    priceMin: 180, priceMax: 320,
    configurations: ['2 BHK (1,600 sqft)', '3 BHK (2,100 sqft)', '3.5 BHK (2,500 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,600 sqft', price: '₹1.8 Cr onwards' },
      { config: '3 BHK', area: '2,100 sqft', price: '₹2.4 Cr onwards' },
      { config: '3.5 BHK', area: '2,500 sqft', price: '₹3.2 Cr onwards' },
    ],
    possession: 'March 2027', totalUnits: 650, totalTowers: 4, totalArea: '8 Acres', floors: 'G+38',
    rera: { number: 'RERA/GGM/2023/445', link: 'https://haryanarera.gov.in' },
    shortDescription: "M3M's premium high-rise on SPR Road with resort-style amenities and strong investment potential.",
    description: "M3M Altitude on Southern Peripheral Road offers premium sky-high living with resort-inspired amenities across 8 acres. Strategically positioned between Golf Course Extension Road and Sohna Road — commanding strong end-user and investor demand. M3M's track record of timely delivery and quality assurance makes this a trusted investment in 2025.",
    highlights: ['Strategic SPR Road location — connects GCER to Sohna Road', 'Resort-style amenities on 5-acre podium', 'RERA-compliant construction-linked payment', 'Strong rental demand from Cyber City professionals', '3.5 BHK — rare configuration with high demand'],
    amenities: ['Resort-Style Clubhouse', 'Temperature-Controlled Pool', 'Gymnasium', 'Meditation Deck', 'Cricket Net', 'Basketball Court', 'Kids Splash Zone', 'Co-Working Lounge', 'Amphitheatre', 'Party Lawn'],
    connectivity: ['Cyber City — 15 km', 'Golf Course Extension Road — 3 km', 'Sohna Road — 4 km', 'NH-48 — 12 km', 'South Point Mall — 6 km', 'IGI Airport — 35 min'],
    nearbyLandmarks: ['GD Goenka School — 5 km', 'Fortis Hospital — 8 km', 'M3M Golfestate — adjacent', 'Vatika Chowk — 7 km'],
    heroImage: IMG.t3, gallery: [IMG.t3, IMG.t5, IMG.pool, IMG.club, IMG.int, IMG.grdn],
    tags: ['premium', 'under-construction', 'spr-road', 'm3m', 'sector-65'],
    appreciationRate: '28–35% (3Y)', rentalYield: '3.0%',
    whyBuy: ['SPR — connects two premium corridors', 'Resort lifestyle at mid-premium price', "M3M's on-time delivery history", 'Strong NRI and investor demand'],
    faqs: [
      { q: 'What is M3M Altitude possession date?', a: 'M3M Altitude is expected to offer possession by March 2027. M3M India has a strong track record of on-time delivery.' },
    ],
    isFeatured: true, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'M3M Altitude Sector 65 Gurgaon – Premium SPR Road 2/3 BHK',
    metaDescription: 'M3M Altitude Sector 65 Gurgaon on SPR Road. 2, 3 & 3.5 BHK premium apartments from ₹1.8 Cr. Get floor plans.',
    metaKeywords: 'M3M Altitude Gurgaon, M3M Sector 65, SPR Road apartments, M3M 3 BHK Gurgaon',
  },

  {
    name: 'M3M Crown',
    slug: 'm3m-crown-sector-111-gurgaon',
    builder: { name: 'M3M India', reraId: 'M3M/HARERA/2023' },
    location: 'Sector 111, Dwarka Expressway, Gurgaon',
    sector: 'Sector 111',
    corridor: 'Dwarka Expressway',
    pincode: '122017',
    status: 'Under Construction',
    priceDisplay: '₹1.2 Cr – ₹2.8 Cr',
    pricePerSqft: '₹8,000 – ₹11,000',
    priceMin: 120, priceMax: 280,
    configurations: ['2 BHK (1,350 sqft)', '3 BHK (1,950 sqft)', '4 BHK (2,600 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,350 sqft', price: '₹1.2 Cr onwards' },
      { config: '3 BHK', area: '1,950 sqft', price: '₹1.7 Cr onwards' },
      { config: '4 BHK', area: '2,600 sqft', price: '₹2.8 Cr onwards' },
    ],
    possession: 'December 2026', totalUnits: 900, totalTowers: 7, totalArea: '14 Acres', floors: 'G+37',
    rera: { number: 'RERA/GGM/2023/490', link: 'https://haryanarera.gov.in' },
    shortDescription: "M3M Crown — premium mid-rise project on Dwarka Expressway near Delhi border.",
    description: "M3M Crown in Sector 111 on Dwarka Expressway is a large-format premium residential development offering 2, 3 and 4 BHK apartments near the Delhi border. The project is well-positioned near IGI Airport and benefits from the Dwarka Expressway's rapid infrastructure growth. With possession expected December 2026, it's an ideal choice for near-ready investment on Gurgaon's fastest-growing corridor.",
    highlights: ['Near Delhi border — best Dwarka Expressway connectivity', 'Large 14-acre township', 'Near possession — December 2026', 'M3M quality construction', 'IGI Airport — 12 min', 'RERA approved'],
    amenities: ['Clubhouse', 'Swimming Pool', 'Gymnasium', 'Tennis Court', 'Basketball Court', 'Kids Zone', 'Jogging Track', 'EV Charging', 'Amphitheatre', 'Community Hall'],
    connectivity: ['Delhi Border — 3 km', 'IGI Airport — 12 min', 'NH-48 — 3 km', 'Dwarka Metro — 9 km', 'Palam Vihar — 6 km', 'Cyber City — 22 min'],
    nearbyLandmarks: ['Ryan International School — 4 km', 'Medanta Hospital — 15 km', 'Pacific D21 Mall — 8 km'],
    heroImage: IMG.t8, gallery: [IMG.t8, IMG.t3, IMG.pool, IMG.gym, IMG.int, IMG.bed],
    tags: ['premium', 'under-construction', 'dwarka-expressway', 'm3m', 'sector-111'],
    appreciationRate: '30–38% (3Y)', rentalYield: '3.5%',
    whyBuy: ['Delhi border proximity — best Dwarka Expressway location', 'M3M brand trust', 'Near possession — low wait risk', 'Strong rental demand from airport zone'],
    faqs: [
      { q: 'What is the price of 3 BHK in M3M Crown?', a: 'M3M Crown 3 BHK starts from ₹1.7 Cr (approx ₹8,700/sqft for 1,950 sqft). Additional charges like PLC and parking apply.' },
    ],
    isFeatured: true, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'M3M Crown Sector 111 Gurgaon – Premium Dwarka Expressway Apartments',
    metaDescription: 'M3M Crown Sector 111 Gurgaon — 2, 3 & 4 BHK premium on Dwarka Expressway from ₹1.2 Cr. Near Delhi border.',
    metaKeywords: 'M3M Crown Gurgaon, M3M Sector 111, Dwarka Expressway apartments, M3M 2 BHK Gurgaon',
  },

  {
    name: 'M3M Antalya Hills',
    slug: 'm3m-antalya-hills-gurgaon',
    builder: { name: 'M3M India', reraId: 'M3M/HARERA/2024' },
    location: 'Sector 79A, SPR Road, Gurgaon',
    sector: 'Sector 79A',
    corridor: 'SPR Road',
    pincode: '122006',
    status: 'New Launch',
    priceDisplay: '₹3.5 Cr – ₹8 Cr',
    pricePerSqft: '₹14,000 – ₹18,000',
    priceMin: 350, priceMax: 800,
    configurations: ['3 BHK (2,150 sqft)', '4 BHK (2,850 sqft)', '4.5 BHK (3,500 sqft)'],
    floorPlans: [
      { config: '3 BHK', area: '2,150 sqft', price: '₹3.5 Cr onwards' },
      { config: '4 BHK', area: '2,850 sqft', price: '₹5 Cr onwards' },
      { config: '4.5 BHK', area: '3,500 sqft', price: '₹8 Cr onwards' },
    ],
    possession: 'June 2028', totalUnits: 580, totalTowers: 5, totalArea: '10 Acres', floors: 'G+40',
    rera: { number: 'RERA/GGM/2024/688', link: 'https://haryanarera.gov.in' },
    shortDescription: "M3M Antalya Hills — Mediterranean luxury living on SPR Road with Aravalli views.",
    description: "M3M Antalya Hills draws inspiration from Turkey's Antalya coast, bringing Mediterranean architecture and resort living to Sector 79A on SPR Road. The project offers premium 3, 4 and 4.5 BHK residences with stunning Aravalli views, a world-class spa and M3M's signature luxury finish. This is one of Gurgaon's most aspirational new launches in 2024–25.",
    highlights: ['Mediterranean-inspired architecture — unique in NCR', 'Aravalli hill views from all units', 'M3M luxury brand flagship', 'SPR Road — high appreciation zone', 'Resort-style living at premium pricing'],
    amenities: ['Mediterranean Clubhouse', 'Infinity Pool with Aravalli View', 'Spa & Turkish Bath', 'Sky Deck', 'Yoga & Meditation', 'Tennis & Squash', 'Golf Simulator', 'Chef\'s Kitchen (events)', 'Pet Park'],
    connectivity: ['Sohna Road — 5 km', 'Golf Course Extension Road — 7 km', 'NH-248A — 4 km', 'Cyber City — 20 km', 'Faridabad — 25 km'],
    nearbyLandmarks: ['Aravalli Biodiversity Park — 2 km', 'GD Goenka School — 8 km', 'Heritage City — 6 km'],
    heroImage: IMG.t6, gallery: [IMG.t6, IMG.t1, IMG.pool, IMG.club, IMG.int, IMG.lob],
    tags: ['luxury', 'new-launch', 'spr-road', 'm3m', 'mediterranean', 'aravalli'],
    appreciationRate: '32–40% (3Y)', rentalYield: '2.8%',
    whyBuy: ['Mediterranean concept — unmatched in NCR', 'Aravalli views — natural premium', 'M3M luxury brand — strong resale demand', 'SPR Road growth corridor'],
    faqs: [
      { q: 'Where is M3M Antalya Hills located?', a: 'M3M Antalya Hills is in Sector 79A on Southern Peripheral Road (SPR Road) in Gurgaon, with Aravalli views and proximity to Sohna Road.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'M3M Antalya Hills Sector 79A Gurgaon – Luxury SPR Road New Launch',
    metaDescription: 'M3M Antalya Hills Gurgaon — Mediterranean luxury 3, 4 BHK on SPR Road from ₹3.5 Cr. Aravalli views. New launch 2025.',
    metaKeywords: 'M3M Antalya Hills, M3M Sector 79A Gurgaon, SPR Road luxury, M3M new launch 2025, Mediterranean apartments Gurgaon',
  },

  {
    name: 'M3M Capital Walk',
    slug: 'm3m-capital-walk-sector-113-gurgaon',
    builder: { name: 'M3M India', reraId: 'M3M/HARERA/2024' },
    location: 'Sector 113, Dwarka Expressway, Gurgaon',
    sector: 'Sector 113',
    corridor: 'Dwarka Expressway',
    pincode: '122017',
    status: 'New Launch',
    priceDisplay: '₹1.5 Cr – ₹3.2 Cr',
    pricePerSqft: '₹9,500 – ₹13,000',
    priceMin: 150, priceMax: 320,
    configurations: ['2 BHK (1,300 sqft)', '3 BHK (2,000 sqft)', '4 BHK (2,600 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,300 sqft', price: '₹1.5 Cr onwards' },
      { config: '3 BHK', area: '2,000 sqft', price: '₹2.2 Cr onwards' },
      { config: '4 BHK', area: '2,600 sqft', price: '₹3.2 Cr onwards' },
    ],
    possession: 'December 2027', totalUnits: 780, totalTowers: 6, totalArea: '11 Acres', floors: 'G+39',
    rera: { number: 'RERA/GGM/2024/112', link: 'https://haryanarera.gov.in' },
    shortDescription: "M3M's new launch in Sector 113 — the best-located sector on Dwarka Expressway, nearest to IGI Airport.",
    description: "M3M Capital Walk in Sector 113 is on Gurgaon's most prime Dwarka Expressway sector — just 7 minutes from IGI Airport and 2 km from the Delhi border. The project offers premium 2, 3 and 4 BHK residences with top-tier amenities and M3M's trusted quality. Sector 113 commands the highest price premium on Dwarka Expressway, ensuring strong appreciation.",
    highlights: ['Sector 113 — best sector on Dwarka Expressway', '7 minutes from IGI Airport', 'New launch pricing — best entry point', 'Metro Phase II proposed nearby', 'M3M premium quality construction'],
    amenities: ['Grand Clubhouse', 'Swimming Pool', 'Gym & Fitness Studio', 'Tennis Court', 'Jogging Track', 'Kids Zone', 'Co-Working Hub', 'EV Charging', 'Amphitheatre', 'Party Hall'],
    connectivity: ['IGI Airport — 7 min', 'Delhi Border — 2 km', 'Dwarka Metro — 8 km', 'NH-48 — 3 km', 'Cyber City — 20 min', 'Dwarka Sector 21 — 10 km'],
    nearbyLandmarks: ['CISF Campus — 3 km', 'Diplomatic Enclave — 9 km', 'Ryan International School — 4 km', 'Pacific D21 Mall — 7 km'],
    heroImage: IMG.t9, gallery: [IMG.t9, IMG.t8, IMG.pool, IMG.gym, IMG.int, IMG.bed],
    tags: ['premium', 'new-launch', 'dwarka-expressway', 'm3m', 'sector-113', 'airport-zone'],
    appreciationRate: '35–42% (3Y)', rentalYield: '3.8%',
    whyBuy: ['Sector 113 — highest Dwarka Expressway premium', 'New launch pricing — best ROI window', 'Airport zone — strong NRI rental demand', 'Metro connectivity boost incoming'],
    faqs: [
      { q: 'Why is Sector 113 the best on Dwarka Expressway?', a: 'Sector 113 is closest to IGI Airport (7 min) and the Delhi border, has the highest price premium, and will benefit most from the upcoming Metro Phase II. M3M Capital Walk offers new launch pricing here.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'M3M Capital Walk Sector 113 Gurgaon – Best Dwarka Expressway New Launch',
    metaDescription: 'M3M Capital Walk Sector 113 Gurgaon — 2, 3 & 4 BHK from ₹1.5 Cr. Airport zone, new launch pricing. RERA approved.',
    metaKeywords: 'M3M Capital Walk, M3M Sector 113 Gurgaon, Dwarka Expressway new launch, property in Sector 113 Gurgaon, near airport property',
  },

  // ════════════ Krisumi ════════════
  {
    name: 'Krisumi Waterside Residences',
    slug: 'krisumi-waterside-residences-gurgaon',
    builder: { name: 'Krisumi Corporation', reraId: 'KRISUMI/HARERA/2024' },
    location: 'Sector 36A, Dwarka Expressway, Gurgaon',
    sector: 'Sector 36A',
    corridor: 'Dwarka Expressway',
    pincode: '122001',
    status: 'New Launch',
    priceDisplay: '₹1.2 Cr – ₹2.8 Cr',
    pricePerSqft: '₹9,500 – ₹12,000',
    priceMin: 120, priceMax: 280,
    configurations: ['2 BHK (1,350 sqft)', '3 BHK (1,900 sqft)', '4 BHK (2,650 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,350 sqft', price: '₹1.2 Cr onwards' },
      { config: '3 BHK', area: '1,900 sqft', price: '₹1.85 Cr onwards' },
      { config: '4 BHK', area: '2,650 sqft', price: '₹2.8 Cr onwards' },
    ],
    possession: 'June 2028', totalUnits: 750, totalTowers: 5, totalArea: '12 Acres', floors: 'G+40',
    rera: { number: 'RERA/GGM/2024/612', link: 'https://haryanarera.gov.in' },
    shortDescription: "Indo-Japanese collaboration — Krisumi's waterfront luxury living at launch pricing on Dwarka Expressway.",
    description: "Krisumi Waterside Residences is a landmark Indo-Japanese collaboration between Krishna Group and Sumitomo Corporation — bringing Japanese precision and Indian warmth to Gurgaon. The project features a stunning water body as the centerpiece, surrounded by lush Japanese gardens and residences designed with minimalist elegance.",
    highlights: ['Indo-Japanese collaboration — Krishna Group x Sumitomo', 'Stunning water body as central feature', 'Japanese minimalist design philosophy', 'Sumitomo\'s engineering precision', 'New launch — best entry pricing', 'RERA registered'],
    amenities: ['Waterfront Clubhouse', 'Japanese Water Garden', 'Infinity Pool', 'Onsen (Japanese Spa)', 'Gymnasium', 'Meditation Pavilion', 'Co-Working', 'Kids Zone', 'Amphitheatre'],
    connectivity: ['IGI Airport — 15 min', 'NH-48 — 2 km', 'Dwarka Metro — 9 km', 'Cyber City — 20 min', 'Delhi border — 2 km'],
    nearbyLandmarks: ['Ryan International — 3 km', 'Sheetla Mata Mandir — 5 km', 'Pacific D21 Mall — 8 km'],
    heroImage: IMG.t7, gallery: [IMG.t7, IMG.t2, IMG.pool, IMG.lob, IMG.int, IMG.grdn],
    tags: ['luxury', 'new-launch', 'dwarka-expressway', 'krisumi', 'japanese-design', 'sector-36a'],
    appreciationRate: '35–45% (3Y)', rentalYield: '3.3%',
    whyBuy: ['Unique Indo-Japanese concept — unmatched in NCR', 'New launch pricing', 'Sumitomo engineering quality', 'Best waterfront design in Gurgaon'],
    faqs: [
      { q: 'Who is Krisumi Corporation?', a: 'Krisumi is a joint venture between Krishna Group (India) and Sumitomo Corporation (Japan) — bringing Japanese construction standards to Indian real estate.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Krisumi Waterside Residences Gurgaon – Indo-Japanese Luxury New Launch',
    metaDescription: 'Krisumi Waterside Residences Gurgaon — Indo-Japanese luxury 2, 3 & 4 BHK from ₹1.2 Cr on Dwarka Expressway. New launch 2025.',
    metaKeywords: 'Krisumi Waterside Residences, Krisumi Gurgaon, Japanese design apartments Gurgaon, Dwarka Expressway new launch, Krisumi Corporation',
  },

  {
    name: 'Krisumi Waterfall Residences',
    slug: 'krisumi-waterfall-residences-gurgaon',
    builder: { name: 'Krisumi Corporation', reraId: 'KRISUMI/HARERA/2020' },
    location: 'Sector 36A, Dwarka Expressway, Gurgaon',
    sector: 'Sector 36A',
    corridor: 'Dwarka Expressway',
    pincode: '122001',
    status: 'Ready To Move',
    priceDisplay: '₹80 Lakh – ₹2 Cr',
    pricePerSqft: '₹6,500 – ₹9,000',
    priceMin: 80, priceMax: 200,
    configurations: ['2 BHK (1,100 sqft)', '3 BHK (1,600 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,100 sqft', price: '₹80 Lakh onwards' },
      { config: '3 BHK', area: '1,600 sqft', price: '₹1.3 Cr onwards' },
    ],
    possession: 'Ready', totalUnits: 540, totalTowers: 4, totalArea: '8 Acres', floors: 'G+35',
    rera: { number: 'RERA/GGM/2020/301', link: 'https://haryanarera.gov.in' },
    shortDescription: "Krisumi's first Gurgaon project — delivered on time with Japanese quality. Ready to move.",
    description: "Krisumi Waterfall Residences was the first project by Krisumi Corporation in Gurgaon and became a benchmark for Indo-Japanese construction quality. Delivered on time, the project features Japanese precision engineering, water-feature landscaping and premium lifestyle. Now ready to move, it offers immediate possession and strong rental returns.",
    highlights: ['Ready to move — immediate possession', 'Krisumi\'s first Gurgaon project — delivered on time', 'Proven Japanese engineering quality', 'Strong rental demand — 3.8% yield', 'Water feature community — unique lifestyle'],
    amenities: ['Waterfall Clubhouse', 'Swimming Pool', 'Gymnasium', 'Jogging Track', 'Kids Zone', 'EV Charging', 'Landscaped Garden'],
    connectivity: ['IGI Airport — 18 min', 'NH-48 — 3 km', 'Dwarka Metro — 10 km', 'Delhi border — 3 km'],
    nearbyLandmarks: ['Ryan International School — 4 km', 'Pacific D21 Mall — 9 km', 'Krisumi Waterside — adjacent (new launch)'],
    heroImage: IMG.t11, gallery: [IMG.t11, IMG.t7, IMG.pool, IMG.gym, IMG.int, IMG.grdn],
    tags: ['premium', 'ready-to-move', 'dwarka-expressway', 'krisumi', 'sector-36a'],
    appreciationRate: '22–28% (3Y)', rentalYield: '3.8%',
    whyBuy: ['Ready to move — no construction wait', 'Krisumi quality — proven delivery', 'Affordable entry vs new launch pricing', 'Immediate rental income opportunity'],
    faqs: [
      { q: 'Is Krisumi Waterfall Residences ready to move?', a: 'Yes. Krisumi Waterfall Residences has received OC and all units are ready for immediate possession. Rental market is strong at 3.8% yield.' },
    ],
    isFeatured: false, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'Krisumi Waterfall Residences Gurgaon – Ready To Move Dwarka Expressway',
    metaDescription: 'Krisumi Waterfall Residences Gurgaon — ready to move 2 & 3 BHK from ₹80 Lakh. Japanese quality. Immediate possession.',
    metaKeywords: 'Krisumi Waterfall Residences, Krisumi Gurgaon, ready to move Dwarka Expressway, 2 bhk Gurgaon affordable',
  },

  // ════════════ Godrej ════════════
  {
    name: 'Godrej Meridien',
    slug: 'godrej-meridien-gurgaon',
    builder: { name: 'Godrej Properties', reraId: 'GODREJ/HARERA/2021' },
    location: 'Sector 106, Dwarka Expressway, Gurgaon',
    sector: 'Sector 106',
    corridor: 'Dwarka Expressway',
    pincode: '122017',
    status: 'Under Construction',
    priceDisplay: '₹95 Lakh – ₹2.2 Cr',
    pricePerSqft: '₹8,000 – ₹9,500',
    priceMin: 95, priceMax: 220,
    configurations: ['2 BHK (1,150 sqft)', '3 BHK (1,680 sqft)', '4 BHK (2,400 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,150 sqft', price: '₹95 Lakh onwards' },
      { config: '3 BHK', area: '1,680 sqft', price: '₹1.4 Cr onwards' },
      { config: '4 BHK', area: '2,400 sqft', price: '₹2.2 Cr onwards' },
    ],
    possession: 'March 2026', totalUnits: 1100, totalTowers: 7, totalArea: '15 Acres', floors: 'G+36',
    rera: { number: 'RERA/GGM/2021/389', link: 'https://haryanarera.gov.in' },
    shortDescription: "Godrej's premium French-themed township on Dwarka Expressway — nearing possession.",
    description: "Godrej Meridien in Sector 106 is a large-format premium residential development offering spacious 2, 3 and 4 BHK apartments with French-themed design and world-class lifestyle infrastructure. Nearing possession with strong OC prospects, Godrej Meridien is ideal for both end-users and investors seeking a near-ready premium home on Dwarka Expressway.",
    highlights: ['Nearing possession — March 2026', "Godrej's transparent pricing, no hidden charges", '15-acre French-themed township', 'Strong rental demand due to airport proximity', 'IGBC Green Gold certification'],
    amenities: ['Grand Clubhouse', 'Olympic Pool', 'Gym', 'Squash Court', 'Tennis Court', 'Jogging Track', 'Kids Zone', 'Amphitheatre', 'Party Hall', 'EV Charging', '5-Tier Security'],
    connectivity: ['IGI Airport — 18 min', 'Dwarka Sector 21 Metro — 9 km', 'NH-48 — 4 km', 'Cyber City — 22 min', 'Palam Vihar Market — 6 km'],
    nearbyLandmarks: ['Ryan International School — 4 km', 'Fortis Hospital — 18 km', 'Ambience Mall — 11 km', 'Ansal University — 5 km'],
    heroImage: IMG.t5, gallery: [IMG.t5, IMG.t3, IMG.pool, IMG.gym, IMG.int, IMG.grdn],
    tags: ['premium', 'under-construction', 'dwarka-expressway', 'godrej', 'sector-106'],
    appreciationRate: '30–38% (3Y)', rentalYield: '3.4%',
    whyBuy: ['Nearing possession — minimal wait risk', 'Godrej brand trust and ethics', 'Best-value 4BHK on Dwarka Expressway', 'Strong rental demand from airport zone'],
    faqs: [
      { q: 'Is Godrej Meridien near possession?', a: 'Yes. Godrej Meridien is in its final stages with possession expected March 2026. Construction is 90%+ complete.' },
      { q: 'What is the price of 3 BHK in Godrej Meridien?', a: '3 BHK starts from ₹1.4 Cr (₹8,500/sqft for 1,680 sqft). PLC, EDC/IDC and parking are additional.' },
    ],
    isFeatured: true, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'Godrej Meridien Sector 106 Gurgaon – Premium Dwarka Expressway Apartments',
    metaDescription: 'Godrej Meridien Sector 106 Gurgaon — 2, 3 & 4 BHK from ₹95 Lakh on Dwarka Expressway. Nearing possession.',
    metaKeywords: 'Godrej Meridien, Godrej Sector 106 Gurgaon, Dwarka Expressway property, 2 BHK Gurgaon, Godrej Properties Gurgaon',
  },

  {
    name: 'Godrej Icon',
    slug: 'godrej-icon-gurgaon',
    builder: { name: 'Godrej Properties', reraId: 'GODREJ/HARERA/2019' },
    location: 'Sector 88A, Dwarka Expressway, Gurgaon',
    sector: 'Sector 88A',
    corridor: 'Dwarka Expressway',
    pincode: '122051',
    status: 'Ready To Move',
    priceDisplay: '₹1.5 Cr – ₹4 Cr',
    pricePerSqft: '₹7,500 – ₹10,500',
    priceMin: 150, priceMax: 400,
    configurations: ['2 BHK (1,350 sqft)', '3 BHK (2,000 sqft)', '4 BHK (2,900 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,350 sqft', price: '₹1.5 Cr onwards' },
      { config: '3 BHK', area: '2,000 sqft', price: '₹2.3 Cr onwards' },
      { config: '4 BHK', area: '2,900 sqft', price: '₹4 Cr onwards' },
    ],
    possession: 'Ready', totalUnits: 850, totalTowers: 6, totalArea: '12 Acres', floors: 'G+34',
    rera: { number: 'RERA/GGM/2019/245', link: 'https://haryanarera.gov.in' },
    shortDescription: "Godrej Icon — ready to move luxury on Dwarka Expressway with Godrej's quality guarantee.",
    description: "Godrej Icon in Sector 88A is a ready-to-move luxury residential development by Godrej Properties on Dwarka Expressway. Designed with an iconic curved facade, the project features premium 2, 3 and 4 BHK residences with top-tier amenities. With OC received, Godrej Icon offers immediate possession and rental income for investors.",
    highlights: ['Ready to move — immediate possession', 'Iconic curved architecture — Gurgaon landmark', 'Godrej zero-defect delivery promise', 'Sector 88A — affordable sector on Dwarka Expressway', 'Strong 3.5% rental yield'],
    amenities: ['Clubhouse', 'Swimming Pool', 'Gymnasium', 'Sports Court', 'Kids Zone', 'Jogging Track', 'Landscaped Garden', 'EV Charging', 'Community Hall'],
    connectivity: ['NH-48 — 5 km', 'IGI Airport — 22 min', 'Dwarka Metro — 12 km', 'Pataudi Road — adjacent', 'Manesar — 18 km'],
    nearbyLandmarks: ['Ryan International School — 6 km', 'Fortis Hospital — 20 km', 'Dwarka City Centre — 12 km'],
    heroImage: IMG.t10, gallery: [IMG.t10, IMG.t5, IMG.pool, IMG.gym, IMG.int, IMG.bed],
    tags: ['premium', 'ready-to-move', 'dwarka-expressway', 'godrej', 'sector-88a'],
    appreciationRate: '20–26% (3Y)', rentalYield: '3.5%',
    whyBuy: ['Ready to move — start living or renting immediately', 'Godrej brand trust', 'Affordable sector with high rental demand', 'Iconic architecture — strong resale premium'],
    faqs: [
      { q: 'Is Godrej Icon ready to move?', a: 'Yes. Godrej Icon has received Occupancy Certificate (OC) and is ready for immediate possession.' },
    ],
    isFeatured: false, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'Godrej Icon Sector 88A Gurgaon – Ready To Move Dwarka Expressway',
    metaDescription: 'Godrej Icon Sector 88A Gurgaon — ready to move 2, 3 & 4 BHK from ₹1.5 Cr on Dwarka Expressway.',
    metaKeywords: 'Godrej Icon Gurgaon, Godrej Sector 88A, ready to move Dwarka Expressway, Godrej Properties Gurgaon',
  },

  {
    name: 'Godrej Nurture',
    slug: 'godrej-nurture-gurgaon',
    builder: { name: 'Godrej Properties', reraId: 'GODREJ/HARERA/2023' },
    location: 'Sector 150, New Gurgaon',
    sector: 'Sector 150',
    corridor: 'New Gurgaon',
    pincode: '122413',
    status: 'Under Construction',
    priceDisplay: '₹60 Lakh – ₹1.5 Cr',
    pricePerSqft: '₹4,500 – ₹6,500',
    priceMin: 60, priceMax: 150,
    configurations: ['2 BHK (1,000 sqft)', '3 BHK (1,500 sqft)', '4 BHK (2,000 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,000 sqft', price: '₹60 Lakh onwards' },
      { config: '3 BHK', area: '1,500 sqft', price: '₹95 Lakh onwards' },
      { config: '4 BHK', area: '2,000 sqft', price: '₹1.5 Cr onwards' },
    ],
    possession: 'December 2027', totalUnits: 1200, totalTowers: 10, totalArea: '20 Acres', floors: 'G+25',
    rera: { number: 'RERA/GGM/2023/568', link: 'https://haryanarera.gov.in' },
    shortDescription: "Godrej Nurture — affordable luxury in New Gurgaon for first-time homebuyers.",
    description: "Godrej Nurture in Sector 150 (New Gurgaon) brings Godrej's trusted quality to the affordable housing segment. Perfect for first-time homebuyers and young families, the project offers 2, 3 and 4 BHK residences with a full suite of lifestyle amenities at Gurgaon's most affordable price points. New Gurgaon is emerging as an IT and industrial hub with strong infrastructure.",
    highlights: ['Most affordable Godrej project in Gurgaon', 'First-time buyer friendly — starts ₹60 Lakh', 'New Gurgaon emerging IT hub', 'KMP Expressway connectivity', '20-acre green township'],
    amenities: ['Clubhouse', 'Swimming Pool', 'Gymnasium', 'Cricket Pitch', 'Kids Zone', 'Community Hall', 'Park', 'Jogging Track', '24/7 Security'],
    connectivity: ['KMP Expressway — 3 km', 'NH-48 — 20 km', 'Manesar — 15 km', 'IMT Manesar — 12 km', 'Gurgaon Railway — 22 km'],
    nearbyLandmarks: ['Manesar Industrial Area — 12 km', 'Global City Gurgaon (proposed) — 5 km', 'New Civil Hospital — 8 km'],
    heroImage: IMG.t12, gallery: [IMG.t12, IMG.t10, IMG.pool, IMG.gym, IMG.int, IMG.grdn],
    tags: ['affordable', 'under-construction', 'new-gurgaon', 'godrej', 'first-time-buyer'],
    appreciationRate: '20–28% (3Y)', rentalYield: '4.5%',
    whyBuy: ['Godrej quality at lowest Gurgaon prices', 'New Gurgaon infrastructure boom', 'Highest rental yield due to industrial demand', 'First-time buyer — RERA protection'],
    faqs: [
      { q: 'Is Godrej Nurture good for investment?', a: 'Yes. New Gurgaon is emerging rapidly. Godrej Nurture offers the trust of Godrej brand at entry-level pricing with 4.5% rental yield from industrial demand.' },
    ],
    isFeatured: false, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Godrej Nurture Sector 150 Gurgaon – Affordable New Gurgaon 2/3 BHK',
    metaDescription: 'Godrej Nurture Sector 150 New Gurgaon — 2 & 3 BHK from ₹60 Lakh. First-time buyer friendly. Godrej quality assured.',
    metaKeywords: 'Godrej Nurture, Godrej Sector 150 Gurgaon, New Gurgaon property, affordable apartments Gurgaon, property in new Gurgaon',
  },

  // ════════════ Oberoi ════════════
  {
    name: 'Oberoi Sky Heights',
    slug: 'oberoi-sky-heights-gurgaon',
    builder: { name: 'Oberoi Realty', reraId: 'OBEROI/HARERA/2023' },
    location: 'Sector 58, Golf Course Extension Road, Gurgaon',
    sector: 'Sector 58',
    corridor: 'Golf Course Extension Road',
    pincode: '122102',
    status: 'Under Construction',
    priceDisplay: '₹4 Cr – ₹10 Cr',
    pricePerSqft: '₹16,000 – ₹22,000',
    priceMin: 400, priceMax: 1000,
    configurations: ['3 BHK (2,400 sqft)', '4 BHK (3,200 sqft)', '5 BHK (4,500 sqft)'],
    floorPlans: [
      { config: '3 BHK', area: '2,400 sqft', price: '₹4 Cr onwards' },
      { config: '4 BHK', area: '3,200 sqft', price: '₹6 Cr onwards' },
      { config: '5 BHK', area: '4,500 sqft', price: '₹10 Cr onwards' },
    ],
    possession: 'March 2028', totalUnits: 420, totalTowers: 4, totalArea: '8 Acres', floors: 'G+45',
    rera: { number: 'RERA/GGM/2023/590', link: 'https://haryanarera.gov.in' },
    shortDescription: "Oberoi Realty's entry into Gurgaon — 5-star ultra-luxury residences on Golf Course Extension Road.",
    description: "Oberoi Sky Heights marks Oberoi Realty's landmark entry into the Gurgaon real estate market — bringing Mumbai's most exclusive developer to Gurgaon's Golf Course Extension Road. The project offers ultra-luxury 3, 4 and 5 BHK sky residences with 5-star hotel-grade amenities, private concierge and Oberoi's legendary service standards.",
    highlights: ['Oberoi Realty\'s first Gurgaon project', '5-star hotel-grade amenities', 'G+45 — panoramic city views', 'Golf Course Extension Road\'s tallest', 'Private concierge for each residence', 'Oberoi brand — Mumbai\'s most premium'],
    amenities: ['5-Star Clubhouse', 'Lap & Leisure Pool', 'Oberoi Spa', 'Sky Bar (45F)', 'Home Theatre Lounge', 'Golf Simulator', 'Business Centre', 'Valet Parking', 'Concierge 24/7', 'EV Super-Charging'],
    connectivity: ['Golf Course Extension Road — direct', 'Golf Course Road — 8 km', 'Cyber City — 12 km', 'NH-48 — 10 km', 'IGI Airport — 28 min'],
    nearbyLandmarks: ['GD Goenka School — 4 km', 'South Point Mall — 5 km', 'Emaar Palm Hills — 3 km', 'Vatika Chowk — 7 km'],
    heroImage: IMG.t1, gallery: [IMG.t1, IMG.t4, IMG.pool, IMG.lob, IMG.int, IMG.bed],
    tags: ['ultra-luxury', 'under-construction', 'golf-course-extension', 'oberoi', 'sector-58', '5-star'],
    appreciationRate: '35–45% (3Y)', rentalYield: '2.5%',
    whyBuy: ['Oberoi brand — India\'s most exclusive developer in Gurgaon', '5-star living — no comparable project', 'Golf Course Extension Road — top luxury corridor', 'Sky Bar & concierge — unique lifestyle'],
    faqs: [
      { q: 'Who is Oberoi Realty?', a: 'Oberoi Realty is one of India\'s most premium real estate developers, known for ultra-luxury projects in Mumbai. Sky Heights is their first project in Gurgaon, bringing Mumbai luxury standards to NCR.' },
      { q: 'What is the starting price of Oberoi Sky Heights?', a: 'Oberoi Sky Heights starts from ₹4 Cr for a 3 BHK (2,400 sqft). The project targets ultra-premium buyers and NRI investors.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Oberoi Sky Heights Sector 58 Gurgaon – 5-Star Ultra Luxury Golf Course Extension',
    metaDescription: 'Oberoi Sky Heights Gurgaon — ultra luxury 3, 4 & 5 BHK from ₹4 Cr. 5-star amenities on Golf Course Extension Road. Oberoi Realty.',
    metaKeywords: 'Oberoi Sky Heights Gurgaon, Oberoi Realty Gurgaon, Golf Course Extension luxury, Sector 58 Gurgaon property, ultra luxury Gurgaon 2025',
  },

  {
    name: 'Oberoi Eternia',
    slug: 'oberoi-eternia-gurgaon',
    builder: { name: 'Oberoi Realty', reraId: 'OBEROI/HARERA/2024' },
    location: 'Sector 58, Golf Course Extension Road, Gurgaon',
    sector: 'Sector 58',
    corridor: 'Golf Course Extension Road',
    pincode: '122102',
    status: 'New Launch',
    priceDisplay: '₹3.5 Cr – ₹8 Cr',
    pricePerSqft: '₹15,000 – ₹20,000',
    priceMin: 350, priceMax: 800,
    configurations: ['3 BHK (2,200 sqft)', '4 BHK (3,000 sqft)', '4.5 BHK (3,600 sqft)'],
    floorPlans: [
      { config: '3 BHK', area: '2,200 sqft', price: '₹3.5 Cr onwards' },
      { config: '4 BHK', area: '3,000 sqft', price: '₹5 Cr onwards' },
      { config: '4.5 BHK', area: '3,600 sqft', price: '₹8 Cr onwards' },
    ],
    possession: 'December 2028', totalUnits: 380, totalTowers: 3, totalArea: '6 Acres', floors: 'G+42',
    rera: { number: 'RERA/GGM/2024/705', link: 'https://haryanarera.gov.in' },
    shortDescription: "Oberoi Eternia — the newest Oberoi luxury tower on Golf Course Extension Road. New launch pricing.",
    description: "Oberoi Eternia is the latest offering from Oberoi Realty in Gurgaon — a luxury high-rise tower in Sector 58 on Golf Course Extension Road adjacent to Oberoi Sky Heights. The project offers 3, 4 and 4.5 BHK residences at new launch pricing, with the same Oberoi signature quality, 5-star amenities and private concierge services.",
    highlights: ['New launch — best pricing before price escalation', 'Oberoi Realty signature quality', 'Adjacent to Oberoi Sky Heights', 'Golf Course Extension Road address', 'Limited 380 units — scarcity premium', 'RERA registered'],
    amenities: ['Grand Clubhouse', 'Infinity Pool', 'Oberoi Wellness Spa', 'Sky Lounge', 'Home Cinema', 'Business Lounge', 'Kids Club', 'Concierge', 'EV Charging', 'Valet Parking'],
    connectivity: ['Golf Course Extension Road — direct', 'Vatika Chowk — 7 km', 'Cyber City — 12 km', 'NH-48 — 10 km'],
    nearbyLandmarks: ['Emaar Palm Hills — 3 km', 'South Point Mall — 5 km', 'GD Goenka School — 4 km'],
    heroImage: IMG.t6, gallery: [IMG.t6, IMG.t1, IMG.pool, IMG.lob, IMG.int, IMG.bed],
    tags: ['luxury', 'new-launch', 'golf-course-extension', 'oberoi', 'sector-58'],
    appreciationRate: '30–40% (3Y)', rentalYield: '2.6%',
    whyBuy: ['Oberoi brand at new launch pricing', 'Best time to enter — pre-price escalation', 'Limited 380 units — scarcity value', 'Golf Course Extension — premium lifestyle corridor'],
    faqs: [
      { q: 'What is the difference between Oberoi Eternia and Sky Heights?', a: 'Both are by Oberoi Realty in Sector 58. Eternia is a new launch (better entry pricing); Sky Heights is under construction (30% price escalated from launch). Both share similar amenities and quality.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Oberoi Eternia Sector 58 Gurgaon – New Launch Golf Course Extension Road',
    metaDescription: 'Oberoi Eternia Gurgaon — new launch luxury 3, 4 & 4.5 BHK from ₹3.5 Cr. Golf Course Extension Road. Oberoi Realty.',
    metaKeywords: 'Oberoi Eternia Gurgaon, Oberoi Sector 58, Golf Course Extension new launch, Oberoi Realty Gurgaon 2025',
  },

  // ════════════ Sobha ════════════
  {
    name: 'Sobha Altus',
    slug: 'sobha-altus-sector-106-gurgaon',
    builder: { name: 'Sobha Limited', reraId: 'SOBHA/HARERA/2024' },
    location: 'Sector 106, Dwarka Expressway, Gurgaon',
    sector: 'Sector 106',
    corridor: 'Dwarka Expressway',
    pincode: '122017',
    status: 'New Launch',
    priceDisplay: '₹3.1 Cr – ₹4.65 Cr',
    pricePerSqft: '₹13,500 – ₹16,000',
    priceMin: 310, priceMax: 465,
    configurations: ['2 BHK (1,850 sqft)', '3 BHK (2,450 sqft)', '4 BHK (3,200 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,850 sqft', price: '₹3.1 Cr onwards' },
      { config: '3 BHK', area: '2,450 sqft', price: '₹3.9 Cr onwards' },
      { config: '4 BHK', area: '3,200 sqft', price: '₹4.65 Cr onwards' },
    ],
    possession: 'December 2028', totalUnits: 835, totalTowers: 5, totalArea: '6.5 Acres', floors: 'G+42',
    rera: { number: 'RERA/GGM/2024/589', link: 'https://haryanarera.gov.in' },
    shortDescription: "Sobha's latest ultra-luxury high-rise on Dwarka Expressway — exceptional build quality with iconic design.",
    description: "Sobha Altus redefines luxury living on Dwarka Expressway with its iconic twin-tower design rising 42 floors above Sector 106. Developed by Sobha Limited — India's most quality-conscious developer — this project offers spacious 2, 3 and 4 BHK sky residences. Every home is built with Sobha's signature quality: in-house construction, imported marble and double-glazed windows.",
    highlights: ["Sobha's iconic quality — in-house construction, zero outsourcing", 'Panoramic Aravalli views from 25th floor', 'IGBC Green Gold certified', 'Private elevator lobbies on premium floors', '5-minute drive to IGI Airport', 'RERA registered'],
    amenities: ['Clubhouse (60,000 sqft)', 'Infinity Pool', 'Sky Lounge (40F)', 'Gym & Yoga Studio', 'Squash & Tennis', 'Jogging Track', 'Co-working Space', 'Kids Zone', 'Golf Simulator', 'EV Charging'],
    connectivity: ['IGI Airport — 5 min', 'NH-48 — 2 km', 'Dwarka Sector 21 Metro — 8 km', 'Cyber City — 20 min', 'Delhi — 12 km'],
    nearbyLandmarks: ['Ryan International School — 3 km', 'Medanta Hospital — 14 km', 'Ambience Mall — 10 km', 'Diplomatic Enclave — 10 km'],
    heroImage: IMG.t1, gallery: [IMG.t1, IMG.t4, IMG.pool, IMG.gym, IMG.int, IMG.bed],
    tags: ['luxury', 'new-launch', 'dwarka-expressway', 'sobha', 'sector-106'],
    appreciationRate: '35–40% (3Y)', rentalYield: '3.2%',
    whyBuy: ['Best-in-class Sobha construction quality', 'Airport zone — 5 min to IGI', 'Limited units ensure scarcity premium', 'Highest ROI corridor in Gurgaon'],
    faqs: [
      { q: 'What is the starting price of Sobha Altus?', a: 'Sobha Altus starts from ₹3.1 Cr for a 2 BHK (1,850 sqft). Additional charges like PLC, EDC/IDC and parking apply.' },
      { q: 'Is Sobha Altus RERA registered?', a: 'Yes. RERA Number: RERA/GGM/2024/589. Verify at haryanarera.gov.in.' },
    ],
    isFeatured: true, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Sobha Altus Sector 106 Gurgaon – Ultra Luxury New Launch Dwarka Expressway',
    metaDescription: 'Sobha Altus Sector 106 Gurgaon — ultra luxury 2, 3 & 4 BHK from ₹3.1 Cr on Dwarka Expressway. 5 min IGI Airport.',
    metaKeywords: 'Sobha Altus Gurgaon, Sobha Sector 106, Dwarka Expressway luxury, new launch Gurgaon 2025, Sobha Limited Gurgaon',
  },

  {
    name: 'Sobha City Gurgaon',
    slug: 'sobha-city-gurgaon',
    builder: { name: 'Sobha Limited', reraId: 'SOBHA/HARERA/2021' },
    location: 'Sector 108, Dwarka Expressway, Gurgaon',
    sector: 'Sector 108',
    corridor: 'Dwarka Expressway',
    pincode: '122017',
    status: 'Under Construction',
    priceDisplay: '₹1 Cr – ₹2.5 Cr',
    pricePerSqft: '₹8,500 – ₹9,800',
    priceMin: 100, priceMax: 250,
    configurations: ['2 BHK (1,250 sqft)', '3 BHK (1,680 sqft)', '4 BHK (2,400 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,250 sqft', price: '₹1 Cr onwards' },
      { config: '3 BHK', area: '1,680 sqft', price: '₹1.6 Cr onwards' },
      { config: '4 BHK', area: '2,400 sqft', price: '₹2.5 Cr onwards' },
    ],
    possession: 'December 2025', totalUnits: 1200, totalTowers: 8, totalArea: '40 Acres', floors: 'G+38',
    rera: { number: 'RERA/GGM/2021/452', link: 'https://haryanarera.gov.in' },
    shortDescription: "Sobha's largest township on Dwarka Expressway — Japanese-inspired design, near possession.",
    description: "Sobha City Gurgaon is a 40-acre integrated township in Sector 108 offering spacious 2, 3 and 4 BHK apartments. Designed with Japanese-style zen landscaping, the project features Sobha's signature quality construction. With possession scheduled for December 2025, this is one of Gurgaon's most anticipated near-ready large-format townships.",
    highlights: ['40-acre integrated township — largest Sobha project', 'Japanese zen landscaping design', 'In-house construction — Sobha quality guarantee', 'Near possession — December 2025', 'IGBC Green Gold certified'],
    amenities: ['Clubhouse (50,000 sqft)', 'Olympic Pool', 'Gym & Yoga', 'Tennis & Badminton', 'Jogging Track', 'Kids Zone', 'Concierge', 'Banquet Hall', 'Temple', 'EV Charging'],
    connectivity: ['IGI Airport — 20 min', 'Dwarka Metro — 11 km', 'NH-48 — 3 km', 'Cyber City — 22 min', 'Pataudi Road — 2 km'],
    nearbyLandmarks: ['DPS Dwarka — 8 km', 'Fortis Hospital — 19 km', 'Pacific D21 Mall — 7 km', 'CISF Campus — 5 km'],
    heroImage: IMG.t8, gallery: [IMG.t8, IMG.t6, IMG.pool, IMG.club, IMG.bed, IMG.lob],
    tags: ['premium', 'under-construction', 'dwarka-expressway', 'sobha', 'sector-108'],
    appreciationRate: '28–35% (3Y)', rentalYield: '3.5%',
    whyBuy: ['Largest Sobha township in Gurgaon', 'Near-possession — December 2025', 'Japanese design — unique lifestyle', 'Airport zone premium — Sector 108'],
    faqs: [
      { q: 'What is the size of Sobha City township?', a: 'Sobha City Gurgaon is spread across 40 acres in Sector 108 — one of the largest gated communities on Dwarka Expressway.' },
    ],
    isFeatured: false, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'Sobha City Gurgaon Sector 108 – 40 Acre Township Dwarka Expressway',
    metaDescription: 'Sobha City Gurgaon Sector 108 — 2, 3 & 4 BHK from ₹1 Cr. 40-acre township. Near possession December 2025.',
    metaKeywords: 'Sobha City Gurgaon, Sobha Sector 108, Dwarka Expressway township, 2 bhk homes in Gurgaon, Sobha under construction',
  },

  // ════════════ Emaar ════════════
  {
    name: 'Emaar Digi Homes',
    slug: 'emaar-digihomes-gurgaon',
    builder: { name: 'Emaar India', reraId: 'EMAAR/HARERA/2020' },
    location: 'Sector 62, Golf Course Extension Road, Gurgaon',
    sector: 'Sector 62',
    corridor: 'Golf Course Extension Road',
    pincode: '122102',
    status: 'Ready To Move',
    priceDisplay: '₹1.2 Cr – ₹3 Cr',
    pricePerSqft: '₹9,800 – ₹13,000',
    priceMin: 120, priceMax: 300,
    configurations: ['2 BHK (1,200 sqft)', '3 BHK (1,850 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,200 sqft', price: '₹1.2 Cr onwards' },
      { config: '3 BHK', area: '1,850 sqft', price: '₹2 Cr onwards' },
    ],
    possession: 'Ready', totalUnits: 460, totalTowers: 4, totalArea: '10 Acres', floors: 'G+35',
    rera: { number: 'RERA/GGM/2020/298', link: 'https://haryanarera.gov.in' },
    shortDescription: "Emaar's smart-home community on Golf Course Extension — ready to move, Dubai quality.",
    description: "Emaar Digi Homes is a ready-to-move smart-home residential community on Golf Course Extension Road. Developed by Emaar India — subsidiary of Dubai's largest real estate developer — the project features integrated smart-home technology, premium specifications and excellent lifestyle infrastructure.",
    highlights: ['Ready to move — immediate possession', "Emaar's Dubai-standard quality", 'Smart-home technology integrated', 'Golf Course Extension Road address', 'Emaar brand — strong resale premium'],
    amenities: ['Smart Clubhouse', 'Pool', 'Gym', 'Smart Co-Work', 'EV Zone', 'Tennis', 'Kids Smart Zone', 'Party Hall'],
    connectivity: ['Cyber City — 10 km', 'NH-48 — 8 km', 'IGI Airport — 28 min', 'Vatika Chowk — 5 km'],
    nearbyLandmarks: ['GD Goenka School — 4 km', 'South Point Mall — 5 km', 'Emaar Palm Hills — adjacent'],
    heroImage: IMG.t9, gallery: [IMG.t9, IMG.t6, IMG.pool, IMG.gym, IMG.int, IMG.lob],
    tags: ['smart-home', 'ready-to-move', 'golf-course-extension', 'emaar', 'sector-62'],
    appreciationRate: '22–28% (3Y)', rentalYield: '3.1%',
    whyBuy: ['Ready to move — start living immediately', 'Emaar brand — Dubai quality in Gurgaon', 'Smart-home tech — unique in this price range'],
    faqs: [
      { q: 'Is Emaar Digi Homes ready to move?', a: 'Yes. Emaar Digi Homes has received OC and all units are ready for immediate possession.' },
    ],
    isFeatured: true, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'Emaar Digi Homes Gurgaon – Ready To Move Smart Homes Golf Course Extension',
    metaDescription: 'Emaar Digi Homes Gurgaon — 2 & 3 BHK smart homes on Golf Course Extension Road from ₹1.2 Cr. Ready to move.',
    metaKeywords: 'Emaar Digi Homes Gurgaon, Emaar India Gurgaon, Golf Course Extension ready to move, smart homes Gurgaon',
  },

  // ════════════ Signature Global ════════════
  {
    name: 'Signature Global City 37D',
    slug: 'signature-global-city-37d-gurgaon',
    builder: { name: 'Signature Global', reraId: 'SIGLOBAL/HARERA/2024' },
    location: 'Sector 37D, Dwarka Expressway, Gurgaon',
    sector: 'Sector 37D',
    corridor: 'Dwarka Expressway',
    pincode: '122006',
    status: 'New Launch',
    priceDisplay: '₹45 Lakh – ₹90 Lakh',
    pricePerSqft: '₹4,500 – ₹5,500',
    priceMin: 45, priceMax: 90,
    configurations: ['2 BHK (870 sqft)', '3 BHK (1,200 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '870 sqft', price: '₹45 Lakh onwards' },
      { config: '3 BHK', area: '1,200 sqft', price: '₹70 Lakh onwards' },
    ],
    possession: 'December 2027', totalUnits: 1400, totalTowers: 12, totalArea: '20 Acres', floors: 'G+25',
    rera: { number: 'RERA/GGM/2024/534', link: 'https://haryanarera.gov.in' },
    shortDescription: "Signature Global's DDJAY affordable housing — best-value 2 BHK for first-time homebuyers in Gurgaon.",
    description: "Signature Global City 37D is one of Gurgaon's most sought-after affordable housing projects under the Deen Dayal Jan Awas Yojana (DDJAY) scheme. Starting ₹45 Lakh for a 2 BHK with RERA protection and metro connectivity — ideal for first-time buyers.",
    highlights: ['DDJAY scheme — government-backed affordable housing', "Signature Global's proven delivery track record", 'Best price per sqft in Gurgaon with metro access', 'Metro Yellow Line at Sector 37 — 3 km'],
    amenities: ['Clubhouse', 'Pool', 'Gym', 'Kids Zone', 'Jogging Track', '24/7 Security', 'Community Hall', 'Park'],
    connectivity: ['Metro Sector 37 — 3 km', 'NH-48 — 5 km', 'Hero Honda Chowk — 5 km', 'Gurgaon Railway Station — 12 km'],
    nearbyLandmarks: ['Sector 37 Metro Station — 3 km', 'IMT Manesar — 18 km'],
    heroImage: IMG.t10, gallery: [IMG.t10, IMG.t11, IMG.pool, IMG.gym, IMG.int, IMG.grdn],
    tags: ['affordable', 'new-launch', 'sector-37d', 'signature-global', 'ddjay', 'first-time-buyer'],
    appreciationRate: '18–22% (3Y)', rentalYield: '4.5%',
    whyBuy: ['Most affordable RERA project in Gurgaon', 'DDJAY — government scheme protection', 'High rental yield from industrial demand'],
    faqs: [
      { q: 'What is the 2 BHK price in Sector 37D Gurgaon?', a: 'Signature Global City 37D offers 2 BHK starting ₹45 Lakh (870 sqft) under DDJAY scheme — the most affordable RERA-approved 2 BHK homes in Gurgaon.' },
    ],
    isFeatured: false, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Signature Global City 37D Gurgaon – Affordable 2 BHK from ₹45 Lakh',
    metaDescription: 'Signature Global City 37D Gurgaon — affordable 2 BHK from ₹45 Lakh under DDJAY. RERA approved. First-time buyer best choice.',
    metaKeywords: '2 bhk homes in Gurgaon affordable, Sector 37D property, Signature Global Gurgaon, DDJAY scheme Gurgaon, affordable property new Gurgaon',
  },

  // ════════════ Tata ════════════
  {
    name: 'Tata One Gurgaon',
    slug: 'tata-one-gurgaon-sector-72',
    builder: { name: 'Tata Housing', reraId: 'TATA/HARERA/2024' },
    location: 'Sector 72, Golf Course Extension Road, Gurgaon',
    sector: 'Sector 72',
    corridor: 'Golf Course Extension Road',
    pincode: '122101',
    status: 'New Launch',
    priceDisplay: '₹60 Lakh – ₹1.5 Cr',
    pricePerSqft: '₹5,800 – ₹7,500',
    priceMin: 60, priceMax: 150,
    configurations: ['1 BHK (650 sqft)', '2 BHK (1,050 sqft)', '3 BHK (1,550 sqft)'],
    floorPlans: [
      { config: '1 BHK', area: '650 sqft', price: '₹60 Lakh onwards' },
      { config: '2 BHK', area: '1,050 sqft', price: '₹90 Lakh onwards' },
      { config: '3 BHK', area: '1,550 sqft', price: '₹1.5 Cr onwards' },
    ],
    possession: 'December 2027', totalUnits: 900, totalTowers: 7, totalArea: '18 Acres', floors: 'G+30',
    rera: { number: 'RERA/GGM/2024/491', link: 'https://haryanarera.gov.in' },
    shortDescription: "Tata Housing's integrated township — Tata ethics, on-time delivery and affordable luxury.",
    description: "Tata One Gurgaon is an integrated township by Tata Housing — India's most ethical real estate developer. Spread across 18 acres in Sector 72 on Golf Course Extension Road, the project offers 1, 2 and 3 BHK residences with premium lifestyle infrastructure and Tata's signature transparency.",
    highlights: ['Tata Housing — India\'s most trusted developer', 'Transparent pricing — no hidden charges', 'Integrated 18-acre township', 'Launch pricing — best time to invest', '1 BHK available — widest buyer pool'],
    amenities: ['Clubhouse', 'Pool', 'Gym', 'Tennis & Badminton', 'Kids Zone', 'Jogging Track', 'Co-Working Hub', 'Mini Theatre', 'Party Hall'],
    connectivity: ['Sohna Road — 5 km', 'NH-48 — 12 km', 'Cyber City — 18 km', 'IGI Airport — 35 min'],
    nearbyLandmarks: ['GD Goenka University — 10 km', 'South Point Mall — 8 km'],
    heroImage: IMG.t11, gallery: [IMG.t11, IMG.t12, IMG.pool, IMG.gym, IMG.bed, IMG.int],
    tags: ['mid-segment', 'new-launch', 'golf-course-extension', 'tata', 'sector-72'],
    appreciationRate: '20–25% (3Y)', rentalYield: '4.0%',
    whyBuy: ['Tata brand — zero compromise on quality', 'Affordable entry on Golf Course Extension', '1 BHK available — widest buyer pool'],
    faqs: [
      { q: 'Is Tata One Gurgaon a good investment?', a: 'Yes. Tata Housing has a perfect delivery track record. 20–25% appreciation expected over 3 years on Golf Course Extension Road.' },
    ],
    isFeatured: false, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Tata One Gurgaon Sector 72 – New Launch Golf Course Extension Road',
    metaDescription: 'Tata One Gurgaon Sector 72 — 1, 2 & 3 BHK from ₹60 Lakh. Trusted Tata Housing. Golf Course Extension Road.',
    metaKeywords: 'Tata One Gurgaon, Tata Housing Gurgaon, Golf Course Extension new launch, 2 bhk Gurgaon affordable',
  },

  // ════════════ BPTP / Hero / Signature (sector coverage) ════════════
  {
    name: 'Hero Homes Sector 104',
    slug: 'hero-homes-sector-104-gurgaon',
    builder: { name: 'Hero Realty', reraId: 'HERO/HARERA/2023' },
    location: 'Sector 104, Dwarka Expressway, Gurgaon',
    sector: 'Sector 104',
    corridor: 'Dwarka Expressway',
    pincode: '122017',
    status: 'Under Construction',
    priceDisplay: '₹80 Lakh – ₹2 Cr',
    pricePerSqft: '₹6,500 – ₹8,500',
    priceMin: 80, priceMax: 200,
    configurations: ['2 BHK (1,200 sqft)', '3 BHK (1,800 sqft)', '4 BHK (2,400 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,200 sqft', price: '₹80 Lakh onwards' },
      { config: '3 BHK', area: '1,800 sqft', price: '₹1.3 Cr onwards' },
      { config: '4 BHK', area: '2,400 sqft', price: '₹2 Cr onwards' },
    ],
    possession: 'June 2026', totalUnits: 750, totalTowers: 6, totalArea: '10 Acres', floors: 'G+30',
    rera: { number: 'RERA/GGM/2023/487', link: 'https://haryanarera.gov.in' },
    shortDescription: "Hero Homes — trusted brand, mid-segment pricing on Dwarka Expressway, near possession.",
    description: "Hero Homes Sector 104 is a mid-segment residential project by Hero Realty — the real estate arm of the Hero Group — on Dwarka Expressway. Nearing possession, the project offers 2, 3 and 4 BHK apartments at attractive pricing with the Hero brand's quality assurance and transparent dealings.",
    highlights: ['Hero Group brand trust', 'Mid-segment pricing — best value Dwarka Expressway', 'Near possession — June 2026', 'RERA registered', 'Sector 104 connectivity'],
    amenities: ['Clubhouse', 'Pool', 'Gym', 'Kids Zone', 'Jogging Track', 'Community Hall', 'EV Charging'],
    connectivity: ['NH-48 — 5 km', 'IGI Airport — 20 min', 'Dwarka Metro — 10 km', 'Palam Vihar — 8 km'],
    nearbyLandmarks: ['Medanta Hospital — 16 km', 'Pacific D21 Mall — 8 km'],
    heroImage: IMG.t12, gallery: [IMG.t12, IMG.t9, IMG.pool, IMG.gym, IMG.int, IMG.grdn],
    tags: ['mid-segment', 'under-construction', 'dwarka-expressway', 'hero-homes', 'sector-104'],
    appreciationRate: '25–32% (3Y)', rentalYield: '3.8%',
    whyBuy: ['Hero brand trust', 'Best value mid-segment on Dwarka Expressway', 'Near possession — low risk', 'Strong airport zone demand'],
    faqs: [
      { q: 'What is the price of 2 BHK in Hero Homes Sector 104?', a: 'Hero Homes Sector 104 offers 2 BHK starting ₹80 Lakh — one of the best-value 2 BHK options on Dwarka Expressway.' },
    ],
    isFeatured: false, isNew: false, isVerified: true, isActive: true,
    metaTitle: 'Hero Homes Sector 104 Gurgaon – Mid Segment Dwarka Expressway',
    metaDescription: 'Hero Homes Sector 104 Gurgaon — 2, 3 & 4 BHK from ₹80 Lakh. Trusted Hero brand. Dwarka Expressway near possession.',
    metaKeywords: 'Hero Homes Gurgaon, Hero Realty Sector 104, Dwarka Expressway mid segment, 2 bhk Gurgaon Dwarka Expressway',
  },

  {
    name: 'Signature Global Titanium SPR',
    slug: 'signature-global-titanium-spr-gurgaon',
    builder: { name: 'Signature Global', reraId: 'SIGLOBAL/HARERA/2023' },
    location: 'Sector 71, SPR Road, Gurgaon',
    sector: 'Sector 71',
    corridor: 'SPR Road',
    pincode: '122004',
    status: 'New Launch',
    priceDisplay: '₹1.2 Cr – ₹2.5 Cr',
    pricePerSqft: '₹7,500 – ₹9,500',
    priceMin: 120, priceMax: 250,
    configurations: ['2 BHK (1,400 sqft)', '3 BHK (2,000 sqft)', '3.5 BHK (2,350 sqft)'],
    floorPlans: [
      { config: '2 BHK', area: '1,400 sqft', price: '₹1.2 Cr onwards' },
      { config: '3 BHK', area: '2,000 sqft', price: '₹1.7 Cr onwards' },
      { config: '3.5 BHK', area: '2,350 sqft', price: '₹2.5 Cr onwards' },
    ],
    possession: 'March 2028', totalUnits: 650, totalTowers: 5, totalArea: '9 Acres', floors: 'G+35',
    rera: { number: 'RERA/GGM/2023/534', link: 'https://haryanarera.gov.in' },
    shortDescription: "Signature Global's premium project on SPR Road — best-value premium 2 & 3 BHK.",
    description: "Signature Global Titanium on SPR Road offers premium 2, 3 and 3.5 BHK residences at competitive pricing on Gurgaon's high-appreciation Southern Peripheral Road. The project is ideally located between Golf Course Extension Road and Sohna Road, commanding strong demand from corporate buyers.",
    highlights: ['Premium pricing at affordable rates', 'SPR Road — connects GCER to Sohna', 'New launch entry pricing', 'Signature Global delivery track record'],
    amenities: ['Clubhouse', 'Pool', 'Gym', 'Tennis', 'Kids Zone', 'Jogging Track', 'EV Charging'],
    connectivity: ['Sohna Road — 4 km', 'Golf Course Extension Road — 5 km', 'NH-48 — 10 km', 'Cyber City — 16 km'],
    nearbyLandmarks: ['GD Goenka School — 6 km', 'Heritage City — 8 km'],
    heroImage: IMG.t3, gallery: [IMG.t3, IMG.t6, IMG.pool, IMG.gym, IMG.int, IMG.grdn],
    tags: ['premium', 'new-launch', 'spr-road', 'signature-global', 'sector-71'],
    appreciationRate: '25–32% (3Y)', rentalYield: '3.5%',
    whyBuy: ['Premium project at mid-segment pricing', 'SPR Road growth corridor', 'Signature Global delivery record'],
    faqs: [
      { q: 'Is SPR Road good for investment in Gurgaon?', a: 'Yes. SPR Road (Southern Peripheral Road) connects Golf Course Extension Road to Sohna Road, making it a strategic corridor with 25–35% appreciation expected over 3 years.' },
    ],
    isFeatured: false, isNew: true, isVerified: true, isActive: true,
    metaTitle: 'Signature Global Titanium Sector 71 Gurgaon – SPR Road New Launch',
    metaDescription: 'Signature Global Titanium Sector 71 Gurgaon on SPR Road — 2, 3 BHK from ₹1.2 Cr. New launch 2025.',
    metaKeywords: 'Signature Global SPR Road, Sector 71 Gurgaon property, on SPR Road property, new projects Gurgaon 2025',
  },
];

// ── Export seedProjects (projects only, used by auto-seed) ────────────────────
async function seedProjects() {
  await Project.deleteMany({});
  await Project.insertMany(PROJECTS);
  console.log(`✅ Seeded ${PROJECTS.length} projects`);
}

// ── Full seed (CLI: npm run seed) ─────────────────────────────────────────────
const seedAll = async () => {
  try {
    await connectDB();
    await Project.deleteMany({});
    await User.deleteMany({});
    console.log('✅ Cleared existing data');

    await Project.insertMany(PROJECTS);
    console.log(`✅ Inserted ${PROJECTS.length} projects (DLF, M3M, Krisumi, Godrej, Oberoi & more)`);

    await User.create({ name: 'Admin', email: 'admin@gurgaonrealty.com', mobile: '9999999999', password: 'Admin@123', role: 'admin' });
    await User.create({ name: 'Sales Manager', email: 'manager@gurgaonrealty.com', mobile: '9988776655', password: 'Manager@123', role: 'manager' });
    await User.create({ name: 'Rahul Sharma', email: 'rahul@gurgaonrealty.com', mobile: '9876543210', password: 'Sales@123', role: 'salesman' });
    console.log('✅ Created admin, manager and salesman users');
    console.log('\n🔑 Admin: admin@gurgaonrealty.com / Admin@123');
    console.log('🔑 Manager: manager@gurgaonrealty.com / Manager@123\n');

    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
};

module.exports = { seedProjects, PROJECTS };

// Run directly: node utils/seedData.js
if (require.main === module) {
  seedAll();
}
